import socket
import json
import os

# --- CONFIGURATION ---
LISTEN_IP = "198.19.10.1"
LISTEN_PORT = 9999
# This is the file generated by your C++ SnapshotManager
SOURCE_JSON_FILE = "../../build/dt_state.json" 

def get_last_snapshot(filepath):
    try:
        if not os.path.exists(filepath):
            return None
        
        with open(filepath, 'r') as f: 
            data = json.load(f)
            if isinstance(data, list) and len(data) > 0:
                return data[-1] # Take the last snapshot in the list
    except Exception as e:
        print(f"[!] Error reading JSON: {e}")
    return None

def main():
    sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    sock.bind((LISTEN_IP, LISTEN_PORT))
    print(f"[*] Responder Ready. Listening on {LISTEN_IP}:{LISTEN_PORT}...")

    while True:
        data, addr = sock.recvfrom(65535) # Larger buffer for complex JSON
        try:
            request = json.loads(data.decode())
            request_id = request.get("id", "unknown")

            if request.get("cmd") == "GET_STATE":
                last_val = get_last_snapshot(SOURCE_JSON_FILE)
                
                if last_val:
                    # Attach the request ID to the snapshot so the collector knows which is which
                    last_val["request_id"] = request_id
                    
                    # Send the JSON snapshot back
                    sock.sendto(json.dumps(last_val).encode(), addr)
                    print(f"[>] Sent last snapshot for ID: {request_id}")
                else:
                    print("[!] No data found in JSON source.")

        except Exception as e:
            print(f"[!] Loop Error: {e}")

if __name__ == "__main__":
    main()
